/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import PHONG.Phong;
import PHONG.QuanLyDanhSachPhong;
import USER.User;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.runApp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtUserPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        pnMainMenu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRoomList = new javax.swing.JButton();
        btnRentedCustomerList = new javax.swing.JButton();
        btnBookedCustomerList = new javax.swing.JButton();
        btnServiceList = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSurchargeList = new javax.swing.JButton();
        btnTurnOver = new javax.swing.JButton();
        pnRoomList = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnRoom101 = new javax.swing.JButton();
        btnRoom102 = new javax.swing.JButton();
        btnRoom103 = new javax.swing.JButton();
        btnRoom104 = new javax.swing.JButton();
        btnRoom105 = new javax.swing.JButton();
        btnRoom205 = new javax.swing.JButton();
        btnRoom201 = new javax.swing.JButton();
        btnRoom202 = new javax.swing.JButton();
        btnRoom203 = new javax.swing.JButton();
        btnRoom204 = new javax.swing.JButton();
        btnRoom301 = new javax.swing.JButton();
        btnRoom302 = new javax.swing.JButton();
        btnRoom304 = new javax.swing.JButton();
        btnRoom303 = new javax.swing.JButton();
        btnRoom305 = new javax.swing.JButton();
        btnRoom401 = new javax.swing.JButton();
        btnRoom405 = new javax.swing.JButton();
        btnRoom403 = new javax.swing.JButton();
        btnRoom402 = new javax.swing.JButton();
        btnRoom404 = new javax.swing.JButton();
        btnRoom501 = new javax.swing.JButton();
        btnRoom503 = new javax.swing.JButton();
        btnRoom505 = new javax.swing.JButton();
        btnRoom502 = new javax.swing.JButton();
        btnRoom504 = new javax.swing.JButton();
        btnRoomListBack = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnLogin.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Khách Sạn");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Đăng nhập");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(508, 134));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Mật khẩu");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 55, -1, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tên đăng nhập");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, 30));

        txtUserName.setBackground(new java.awt.Color(255, 255, 255));
        txtUserName.setName(""); // NOI18N
        txtUserName.setNextFocusableComponent(txtUserPassword);
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 19, 350, 30));

        txtUserPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtUserPassword.setNextFocusableComponent(btnLogin);
        jPanel1.add(txtUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 58, 350, 30));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Đăng nhập");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        javax.swing.GroupLayout pnLoginLayout = new javax.swing.GroupLayout(pnLogin);
        pnLogin.setLayout(pnLoginLayout);
        pnLoginLayout.setHorizontalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLoginLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnLoginLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoginLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnLoginLayout.setVerticalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pnMainMenu.setBackground(new java.awt.Color(204, 255, 255));
        pnMainMenu.setVerifyInputWhenFocusTarget(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quản Lý Khách Sạn");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Vui lòng chọn chức năng");
        jLabel6.setToolTipText("");

        btnRoomList.setBackground(new java.awt.Color(255, 255, 255));
        btnRoomList.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoomList.setForeground(new java.awt.Color(0, 0, 0));
        btnRoomList.setText("Danh Sách Phòng");
        btnRoomList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomListActionPerformed(evt);
            }
        });

        btnRentedCustomerList.setBackground(new java.awt.Color(255, 255, 255));
        btnRentedCustomerList.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRentedCustomerList.setForeground(new java.awt.Color(0, 0, 0));
        btnRentedCustomerList.setText("Danh Sách Khách Thuê");

        btnBookedCustomerList.setBackground(new java.awt.Color(255, 255, 255));
        btnBookedCustomerList.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnBookedCustomerList.setForeground(new java.awt.Color(0, 0, 0));
        btnBookedCustomerList.setText("Danh Sách Khách Đặt");

        btnServiceList.setBackground(new java.awt.Color(255, 255, 255));
        btnServiceList.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnServiceList.setForeground(new java.awt.Color(0, 0, 0));
        btnServiceList.setText("Danh Sách Dịch Vụ");

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setText("Đăng Xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setText("Thoát Chương Trình");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSurchargeList.setBackground(new java.awt.Color(255, 255, 255));
        btnSurchargeList.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnSurchargeList.setForeground(new java.awt.Color(0, 0, 0));
        btnSurchargeList.setText("Danh Sách Phụ Thu");

        btnTurnOver.setBackground(new java.awt.Color(255, 255, 255));
        btnTurnOver.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnTurnOver.setForeground(new java.awt.Color(0, 0, 0));
        btnTurnOver.setText("Doanh Thu");

        javax.swing.GroupLayout pnMainMenuLayout = new javax.swing.GroupLayout(pnMainMenu);
        pnMainMenu.setLayout(pnMainMenuLayout);
        pnMainMenuLayout.setHorizontalGroup(
            pnMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainMenuLayout.createSequentialGroup()
                .addGroup(pnMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMainMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnMainMenuLayout.createSequentialGroup()
                        .addGroup(pnMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnMainMenuLayout.createSequentialGroup()
                                .addGap(317, 317, 317)
                                .addGroup(pnMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnServiceList, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBookedCustomerList, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRentedCustomerList, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRoomList, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSurchargeList, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTurnOver, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnMainMenuLayout.createSequentialGroup()
                                .addGap(347, 347, 347)
                                .addComponent(jLabel6)))
                        .addGap(0, 323, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnMainMenuLayout.setVerticalGroup(
            pnMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(btnRoomList)
                .addGap(18, 18, 18)
                .addComponent(btnRentedCustomerList)
                .addGap(18, 18, 18)
                .addComponent(btnBookedCustomerList)
                .addGap(18, 18, 18)
                .addComponent(btnServiceList)
                .addGap(18, 18, 18)
                .addComponent(btnSurchargeList)
                .addGap(18, 18, 18)
                .addComponent(btnTurnOver)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pnRoomList.setBackground(new java.awt.Color(204, 255, 255));
        pnRoomList.setForeground(new java.awt.Color(0, 0, 0));
        pnRoomList.setPreferredSize(new java.awt.Dimension(973, 588));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DANH SÁCH PHÒNG");
        jLabel7.setToolTipText("");

        btnRoom101.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom101.setText("Phòng 101");

        btnRoom102.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom102.setText("Phòng 102");

        btnRoom103.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom103.setText("Phòng 103");

        btnRoom104.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom104.setText("Phòng 104");

        btnRoom105.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom105.setText("Phòng 105");

        btnRoom205.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom205.setText("Phòng 205");

        btnRoom201.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom201.setText("Phòng 201");

        btnRoom202.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom202.setText("Phòng 202");

        btnRoom203.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom203.setText("Phòng 203");

        btnRoom204.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom204.setText("Phòng 204");

        btnRoom301.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom301.setText("Phòng 301");

        btnRoom302.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom302.setText("Phòng 302");

        btnRoom304.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom304.setText("Phòng 304");

        btnRoom303.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom303.setText("Phòng 303");

        btnRoom305.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom305.setText("Phòng 305");

        btnRoom401.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom401.setText("Phòng 401");

        btnRoom405.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom405.setText("Phòng 405");

        btnRoom403.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom403.setText("Phòng 403");

        btnRoom402.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom402.setText("Phòng 402");

        btnRoom404.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom404.setText("Phòng 404");

        btnRoom501.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom501.setText("Phòng 501");

        btnRoom503.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom503.setText("Phòng 503");

        btnRoom505.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom505.setText("Phòng 505");

        btnRoom502.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom502.setText("Phòng 502");

        btnRoom504.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoom504.setText("Phòng 504");

        btnRoomListBack.setText("Trở về");
        btnRoomListBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomListBackActionPerformed(evt);
            }
        });

        jPanel5.setBackground(java.awt.Color.green);
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.setBackground(java.awt.Color.red);
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Có khách");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Đang dọn dẹp");

        jPanel3.setBackground(java.awt.Color.yellow);
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Phòng trống");

        javax.swing.GroupLayout pnRoomListLayout = new javax.swing.GroupLayout(pnRoomList);
        pnRoomList.setLayout(pnRoomListLayout);
        pnRoomListLayout.setHorizontalGroup(
            pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRoomListLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRoomListLayout.createSequentialGroup()
                        .addComponent(btnRoom501, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom502, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom503, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom504, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom505, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnRoomListLayout.createSequentialGroup()
                        .addComponent(btnRoom401, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom402, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom403, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom404, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom405, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnRoomListLayout.createSequentialGroup()
                        .addComponent(btnRoom301, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom302, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom303, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom304, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom305, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnRoomListLayout.createSequentialGroup()
                        .addComponent(btnRoom201, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom202, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom203, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom204, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom205, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnRoomListLayout.createSequentialGroup()
                        .addComponent(btnRoom101, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom102, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom103, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom104, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoom105, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRoomListBack))
                .addGap(0, 99, Short.MAX_VALUE))
            .addGroup(pnRoomListLayout.createSequentialGroup()
                .addGroup(pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRoomListLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnRoomListLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnRoomListLayout.setVerticalGroup(
            pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRoomListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(btnRoomListBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRoom101, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom102, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom103, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom104, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom105, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRoom201, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom202, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom203, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom204, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom205, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRoom301, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom302, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom303, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom304, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom305, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRoom401, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom402, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom403, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom404, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom405, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRoom501, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom502, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom503, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom504, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom505, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnRoomListLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnRoomListLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnRoomList, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnRoomList, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pnMainMenu.getAccessibleContext().setAccessibleParent(this);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String userName = txtUserName.getText();
        String userPassword = txtUserPassword.getText();
        
        if (userName.isBlank() || userPassword.isBlank()) {
            JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không được để trống.");
        }
        else {
            boolean isAuthen = false;
            try {
                isAuthen = this.userAuthenciation(userName, userPassword);
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(isAuthen) {
                txtUserName.setText("");
                txtUserPassword.setText("");
                this.goToMainMenu();
            }
            else 
                JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không chính xác.");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.goToLogin();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRoomListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomListActionPerformed
        try {
            // TODO add your handling code here:
            this.goToRoomList();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRoomListActionPerformed

    private void btnRoomListBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomListBackActionPerformed
        // TODO add your handling code here:
        this.goToMainMenu();
    }//GEN-LAST:event_btnRoomListBackActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:
            this.connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    private final Color[] ROOM_STATUS_COLOR = {Color.GREEN, Color.RED, Color.YELLOW};
    
    private Connection connection;
    private Statement statement;
    
    private User currentUser;
    private QuanLyDanhSachPhong roomList;
    private Map<String, JButton> btnMap;
    
    public void mappingBtn() {
        this.btnMap = new HashMap<>();
        
        this.btnMap.put("101", btnRoom101);
        this.btnMap.put("102", btnRoom102);
        this.btnMap.put("103", btnRoom103);
        this.btnMap.put("104", btnRoom104);
        this.btnMap.put("105", btnRoom105);
        this.btnMap.put("201", btnRoom201);
        this.btnMap.put("202", btnRoom202);
        this.btnMap.put("203", btnRoom203);
        this.btnMap.put("204", btnRoom204);
        this.btnMap.put("205", btnRoom205);
        this.btnMap.put("301", btnRoom301);
        this.btnMap.put("302", btnRoom302);
        this.btnMap.put("303", btnRoom303);
        this.btnMap.put("304", btnRoom304);
        this.btnMap.put("305", btnRoom305);
        this.btnMap.put("401", btnRoom401);
        this.btnMap.put("402", btnRoom402);
        this.btnMap.put("403", btnRoom403);
        this.btnMap.put("404", btnRoom404);
        this.btnMap.put("405", btnRoom405);
        this.btnMap.put("501", btnRoom501);
        this.btnMap.put("502", btnRoom502);
        this.btnMap.put("503", btnRoom503);
        this.btnMap.put("504", btnRoom504);
        this.btnMap.put("505", btnRoom505);
    }
    
    public void goToMainMenu() {
        pnLogin.setVisible(false);
        pnMainMenu.setVisible(true);
        pnRoomList.setVisible(false);
    }
    
    public void goToLogin(){
        pnLogin.setVisible(true);
        pnMainMenu.setVisible(false);
        pnRoomList.setVisible(false);
    }
    
    public void goToRoomList() throws SQLException{
        pnLogin.setVisible(false);
        pnMainMenu.setVisible(false);
        pnRoomList.setVisible(true);
        
        this.loadingRoomList();
    }
    
    public void connectingToDB(){
        /*Connect to SQL server*/
        Connection conn = null;
        while(true) {
            try {
                String dbURL = "jdbc:sqlserver://localhost:1433;instance=LAPTOP-BS1VBGIV;databaseName=OOP;encrypt=true;trustServerCertificate=true";
                String user = "sa";
                String pass = "a0964278425";
                conn = DriverManager.getConnection(dbURL, user, pass);
                if (conn != null) {
                    this.connection = conn;
                    Statement stmt = conn.createStatement();
                    this.statement = stmt;
                    break;
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                int result = JOptionPane.showConfirmDialog(this, "Kết nối dữ liệu không thành công.\n Bạn có muốn thử lại?", "Kết nối thất bại", JOptionPane.YES_NO_OPTION);
                if(result != 0) {
                    System.exit(0);
                    break;
                }
            }
        }
    }
    
    public boolean userAuthenciation(String userName, String userPassword) throws SQLException{
        ResultSet result = statement.executeQuery("SELECT * FROM TAIKHOAN");
        while(result.next()) {
            if (userName.equals(result.getString(1)) && userPassword.equals(result.getString(2))) {
                this.currentUser = new User(result.getString(1), result.getString(2), Integer.parseInt(result.getString(3)));
                return true;
            }
        }
        return false;
    }
    
    public void loadingRoomList() throws SQLException{
        if (this.roomList.layDanhSach().isEmpty()) {
            ResultSet result = statement.executeQuery("SELECT * FROM PHONG");
            
            while(result.next()) {
                Phong p = new Phong(result.getString(1), Integer.parseInt(result.getString(2)), result.getString(1));
                this.roomList.themPhong(p);
            }
        }
        
        for(Phong p: roomList.layDanhSach()) {
            this.btnMap.get(p.getMaPhong()).setBackground(ROOM_STATUS_COLOR[p.getTrangThai()]);
        }
    }
    
    public void runApp() {
        this.goToLogin();
        
        this.connectingToDB();
        this.mappingBtn();
        
        this.roomList = new QuanLyDanhSachPhong();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookedCustomerList;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRentedCustomerList;
    private javax.swing.JButton btnRoom101;
    private javax.swing.JButton btnRoom102;
    private javax.swing.JButton btnRoom103;
    private javax.swing.JButton btnRoom104;
    private javax.swing.JButton btnRoom105;
    private javax.swing.JButton btnRoom201;
    private javax.swing.JButton btnRoom202;
    private javax.swing.JButton btnRoom203;
    private javax.swing.JButton btnRoom204;
    private javax.swing.JButton btnRoom205;
    private javax.swing.JButton btnRoom301;
    private javax.swing.JButton btnRoom302;
    private javax.swing.JButton btnRoom303;
    private javax.swing.JButton btnRoom304;
    private javax.swing.JButton btnRoom305;
    private javax.swing.JButton btnRoom401;
    private javax.swing.JButton btnRoom402;
    private javax.swing.JButton btnRoom403;
    private javax.swing.JButton btnRoom404;
    private javax.swing.JButton btnRoom405;
    private javax.swing.JButton btnRoom501;
    private javax.swing.JButton btnRoom502;
    private javax.swing.JButton btnRoom503;
    private javax.swing.JButton btnRoom504;
    private javax.swing.JButton btnRoom505;
    private javax.swing.JButton btnRoomList;
    private javax.swing.JButton btnRoomListBack;
    private javax.swing.JButton btnServiceList;
    private javax.swing.JButton btnSurchargeList;
    private javax.swing.JButton btnTurnOver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pnLogin;
    private javax.swing.JPanel pnMainMenu;
    private javax.swing.JPanel pnRoomList;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
